### ISSUE TITLE
Email Stuff

### ISSUE THREAD

**Issue by j-jasik** [betheluniversity/writing-center-python#118]
Move Email Preferences to the profile page and make them simple checkboxes.

Only admins should have access to the email functionalities.

There is a FERPA agreement required for some emails.

**Comment by bak45247** [comment]
**@j-jasik can we get some more info on FERPA?**

**Comment by j-jasik** [comment]
So I just looked through the PHP code and it looks like the "FERPA Agreement" is just a checkbox in the end of appointment form. If it's checked, an email is sent to the student's professor, if it's not no email gets sent.

**Comment by j-jasik** [comment]
All of my comments from the original issue are completed so I am closing this issue.
