### ISSUE TITLE
Appointments viewable until start

### ISSUE THREAD

**Issue by j-jasik** [betheluniversity/writing-center-python#137]
Any open appointments should be visible until they reach their start time. That way, if a student wants to sign up for an appointment 10 minutes before it's scheduled they can still see it. (Apparently in the current app they disappear about an hour ahead of time)

**Comment by bam95899** [comment]
@j-jasik Right now in the WC-python app it is setup so you can view and schedule open appointments as long as they are how ever many hours in the future as specified by the time setting, thus if the time setting is set to 0, then you can sign up for an appointment as long as it hasn't already started. Let me know if you want me to remove the time setting aspect of it, although that I'm pretty sure that is the whole reason we have a time setting.

**Comment by j-jasik** [comment]
Yeah @bam95899 I think that's good. Apparently in the old app that was the way it was supposed to work but for some reason appointments still disappeared about an hour ahead of time. If this is already good to go in our version feel free to close this issue!
