### ISSUE TITLE
Send Email Functionality

### ISSUE THREAD

**Issue by j-jasik** [betheluniversity/writing-center-python#15]
Make this functionality more like tutorlabs using Flask-Mail. Need to be able to manage message preferences and send emails to users, tutors, and students.

**Comment by bak45247** [comment]
- [ ] Substitute Emails
- [ ] Message Center Emails
- [ ] Session Emails
- [ ] Appointment Signup Emails

**Comment by bak45247** [comment]
hrefs in email templates have endpoints now

**Comment by bak45247** [comment]
DONE
