### ISSUE TITLE
Calendar Colors and Text

### ISSUE THREAD

**Issue by j-jasik** [betheluniversity/writing-center-python#163]
Make sure the text is nice and readable on the calendars, specifically for the blue background. Maybe change that one to white text.

**Comment by j-jasik** [comment]
Along with the slightly duller shade of yellow (which still needs to be done) if we can change the text on the calendar to be more easily readable that would be good too. Caleb suggested white text for the blue and green backgrounds, as well as maybe for the orange if it looks better.

Also, we should put the tutors names on the calendar rather than their username.

**Comment by bak45247** [comment]
colors changed, looking at Jordan to get the changes approved by April

**Comment by j-jasik** [comment]
Sent to April, I'll let you know what I hear back.
