### ISSUE TITLE
End Appointment Cron

### ISSUE THREAD

**Issue by j-jasik** [betheluniversity/writing-center-python#230]
@c-schwarze I wanted to know what you think about adding a cron to close appointments that get left open. It's happened a few times this semester already so I'm thinking it might be a good idea.

**Comment by c-schwarze** [comment]
Yeah I think that seems like a good idea. What time would you put - the time that its closed (11:55pm)?

**Comment by j-jasik** [comment]
I think that makes sense. It would easily identify itself as being ended by the cron then. No real appointments happen that late.
