### ISSUE TITLE
View Your Appointments Button Doesn't Work

### ISSUE THREAD

**Issue by bak45247** [betheluniversity/writing-center-python#242]
The button to view your appointments in the `schedules/view-tutor-schedules` endpoint doesn't work correctly. 

Clicking will reveal your appointments, but clicking again doesn't bring all the open appointments back.

**Comment by bam95899** [comment]
The "View Open Appointments" button brings up open appointments in the sense that someone has requested a sub those appointments. I tested it locally and it seems to be working correctly.
